import streamlit as st
import datetime
from agent.agentic_workflow import GraphBuilder

st.set_page_config(
    page_title="🌍 Travel Planner Agentic Application",
    page_icon="🌍",
    layout="centered",
    initial_sidebar_state="expanded",
)

st.title("🌍 Travel Planner Agentic Application")

# Initialize chat history
if "messages" not in st.session_state:
    st.session_state.messages = []

# Build the AI travel agent once per session
@st.cache_resource
def get_travel_agent():
    builder = GraphBuilder(model_provider="groq")
    return builder()

travel_agent = get_travel_agent()

# Display chat history
st.header("How can I help you in planning a trip? Let me know where do you want to visit.")

# Chat input box at bottom
with st.form(key="query_form", clear_on_submit=True):
    user_input = st.text_input("User Input", placeholder="e.g. Plan a trip to Goa for 5 days")
    submit_button = st.form_submit_button("Send")

if submit_button and user_input.strip():
    try:
        with st.spinner("Bot is thinking..."):
            messages = {"messages": [user_input]}
            output = travel_agent.invoke(messages)

        if isinstance(output, dict) and "messages" in output:
            answer = output["messages"][-1].content
        else:
            answer = str(output)

        markdown_content = f"""# 🌍 AI Travel Plan

        # **Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}  
        # **Created by:** Atriyo's Travel Agent

        ---

        {answer}

        ---

        *This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*
        """
        st.markdown(markdown_content)
    except Exception as e:
        raise Exception(f"The response failed due to {e}")